Qry1="CREATE TEMPORARY TABLE IF NOT EXISTS tempTable1 ENGINE=MEMORY AS (select * from BYDY_RISK_NTC_PRTC where OCR_DTM < NOW() AND OCR_DTM > SUBDATE(NOW(), INTERVAL 30 SECOND) AND SEND_PROC_TP=01)"
#Qry1="CREATE TEMPORARY TABLE IF NOT EXISTS tempTable1 ENGINE=MEMORY AS (select * from BYDY_RISK_NTC_PRTC where OCR_DTM < SUBDATE(NOW(), INTERVAL 30 SECOND) AND OCR_DTM > SUBDATE(NOW(), INTERVAL 300 SECOND) AND SEND_PROC_TP=01)"
Qry2="select OCR_DTM, RISK_CLS_TP, SRVR_NM, TR_NM, SUM_CNT, HIGH_CALC_CNT, LOW_CALC_CNT, count(SRVR_NM) from tempTable1 group by RISK_CLS_TP, SRVR_NM, TR_NM"
Qry3="select * from BYDY_RISK_NTC_PRTC where OCR_DTM < SUBDATE(NOW(), INTERVAL 30 SECOND) AND OCR_DTM > SUBDATE(NOW(), INTERVAL 300 SECOND) AND SEND_PROC_TP=01"
#Qry3="select OCR_DTM, DATA_SUM_TP, COUNT(*) from tempTable1 where OCR_DTM < NOW() AND OCR_DTM > SUBDATE(NOW(), INTERVAL 30 SECOND) AND SEND_PROC_TP=01 group by DATA_SUM_TP"
#Qry4="select OCR_DTM, RISK_CLS_TP, COUNT(*) from tempTable1 where OCR_DTM < NOW() AND OCR_DTM > SUBDATE(NOW(), INTERVAL 30 SECOND) AND SEND_PROC_TP=01 group by RISK_CLS_TP"
Qry5="select SRVR_NM, TR_NM, count(SRVR_NM) from BYDY_RISK_NTC_PRTC group by SRVR_NM, TR_NM LIMIT 10"


